[package]
name = "webidentity"
version = "0.2.0"
edition = "2021"

[dependencies]
lol_html = "2.6.0"
url = "2.4"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
thiserror = "1.0"
